# SUSL Hostel Management System - Ultra-Minimal Nixpacks Configuration
# Only base PHP 8.2 to avoid extension conflicts

[phases.setup]
nixPkgs = ["php82"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
PHP_VERSION = "8.2"
COMPOSER_ALLOW_SUPERUSER = "1"