<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SUSL Student Report - {{ $hostel !== 'all' ? $hostel : 'All Hostels' }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #0066cc;
            padding-bottom: 15px;
        }
        
        .header h1 {
            color: #0066cc;
            font-size: 24px;
            margin: 0 0 5px 0;
            font-weight: bold;
        }
        
        .header h2 {
            color: #666;
            font-size: 16px;
            margin: 0 0 10px 0;
            font-weight: normal;
        }
        
        .header .subtitle {
            color: #888;
            font-size: 14px;
            margin: 5px 0;
        }
        
        .report-info {
            background-color: #f8f9fa;
            padding: 15px;
            margin-bottom: 20px;
            border-left: 4px solid #0066cc;
        }
        
        .report-info table {
            width: 100%;
            border-collapse: collapse;
        }
        
        .report-info td {
            padding: 5px 10px;
            border: none;
        }
        
        .report-info .label {
            font-weight: bold;
            color: #0066cc;
            width: 30%;
        }
        
        .students-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        
        .students-table th {
            background-color: #0066cc;
            color: white;
            padding: 12px 8px;
            text-align: left;
            font-weight: bold;
            font-size: 11px;
        }
        
        .students-table td {
            padding: 10px 8px;
            border-bottom: 1px solid #ddd;
            vertical-align: top;
            font-size: 10px;
        }
        
        .students-table tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        
        .students-table tr:hover {
            background-color: #e3f2fd;
        }
        
        .student-name {
            font-weight: bold;
            color: #0066cc;
        }
        
        .reg-number {
            color: #666;
            font-size: 9px;
            margin-top: 2px;
        }
        
        .contact-info {
            font-size: 9px;
            color: #555;
        }
        
        .hostel-info {
            font-size: 9px;
            background-color: #e8f5e8;
            padding: 3px 6px;
            border-radius: 3px;
            display: inline-block;
            margin: 1px 0;
        }
        
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 2px solid #0066cc;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        
        .page-break {
            page-break-before: always;
        }
        
        .no-students {
            text-align: center;
            padding: 40px;
            color: #666;
            font-style: italic;
        }
        
        @media print {
            body {
                margin: 0;
                padding: 15px;
            }
            
            .students-table {
                font-size: 9px;
            }
            
            .students-table th {
                font-size: 10px;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Sabaragamuwa University of Sri Lanka</h1>
        <h2>Student Hostel Management System</h2>
        <div class="subtitle">Student Details Report</div>
    </div>

    <div class="report-info">
        <table>
            <tr>
                <td class="label">Report Type:</td>
                <td>{{ $hostel !== 'all' ? 'Hostel-wise Student Details' : 'All Students Details' }}</td>
                <td class="label">Total Students:</td>
                <td><strong>{{ $total_students }}</strong></td>
            </tr>
            <tr>
                <td class="label">Hostel Filter:</td>
                <td>{{ $hostel !== 'all' ? $hostel : 'All Hostels' }}</td>
                <td class="label">Year Filter:</td>
                <td>{{ $year !== 'all' ? ucfirst($year) . ' Year' : 'All Years' }}</td>
            </tr>
            <tr>
                <td class="label">Generated On:</td>
                <td>{{ $generated_at }}</td>
                <td class="label">Generated By:</td>
                <td>{{ $generated_by }}</td>
            </tr>
        </table>
    </div>

    @if($students->count() > 0)
        <table class="students-table">
            <thead>
                <tr>
                    <th style="width: 5%;">#</th>
                    <th style="width: 20%;">Student Details</th>
                    <th style="width: 15%;">Faculty & Degree</th>
                    <th style="width: 15%;">Contact Information</th>
                    <th style="width: 25%;">Hostel Information</th>
                    <th style="width: 20%;">Parent/Guardian Details</th>
                </tr>
            </thead>
            <tbody>
                @foreach($students as $index => $student)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>
                        <div class="student-name">{{ $student->full_name }}</div>
                        <div class="reg-number">Reg: {{ $student->registration_number }}</div>
                        <div class="reg-number">Index: {{ $student->index_number }}</div>
                        <div class="reg-number">NIC: {{ $student->nic_number }}</div>
                        <div class="reg-number">DOB: {{ \Carbon\Carbon::parse($student->date_of_birth)->format('Y-m-d') }}</div>
                    </td>
                    <td>
                        <div><strong>{{ $student->faculty }}</strong></div>
                        <div style="margin-top: 5px; font-size: 9px;">{{ $student->degree_program }}</div>
                        <div style="margin-top: 3px; font-size: 9px; color: #666;">{{ $student->current_year }} Year</div>
                    </td>
                    <td class="contact-info">
                        <div><strong>Mobile:</strong> {{ $student->mobile_number }}</div>
                        <div style="margin-top: 3px;"><strong>Email:</strong> {{ $student->email }}</div>
                        <div style="margin-top: 5px;"><strong>Home Address:</strong></div>
                        <div style="margin-top: 2px;">{{ $student->home_address }}</div>
                    </td>
                    <td>
                        @if($student->first_year_hostel && $student->first_year_hostel !== 'Off Campus')
                            <div class="hostel-info">1st Year: {{ $student->first_year_hostel }}</div>
                        @endif
                        @if($student->second_year_hostel && $student->second_year_hostel !== 'Off Campus')
                            <div class="hostel-info">2nd Year: {{ $student->second_year_hostel }}</div>
                        @endif
                        @if($student->third_year_hostel && $student->third_year_hostel !== 'Off Campus')
                            <div class="hostel-info">3rd Year: {{ $student->third_year_hostel }}</div>
                        @endif
                        @if($student->fourth_year_hostel && $student->fourth_year_hostel !== 'Off Campus')
                            <div class="hostel-info">4th Year: {{ $student->fourth_year_hostel }}</div>
                        @endif
                        @if(!$student->first_year_hostel && !$student->second_year_hostel && !$student->third_year_hostel && !$student->fourth_year_hostel)
                            <div style="color: #999; font-style: italic;">No hostel information</div>
                        @endif
                    </td>
                    <td class="contact-info">
                        <div><strong>Parent/Guardian:</strong> {{ $student->parent_guardian_name }}</div>
                        <div style="margin-top: 3px;"><strong>Contact:</strong> {{ $student->parent_guardian_contact }}</div>
                        <div style="margin-top: 5px;"><strong>Address:</strong></div>
                        <div style="margin-top: 2px;">{{ $student->parent_guardian_address }}</div>
                    </td>
                </tr>
                
                @if(($index + 1) % 10 == 0 && $index + 1 < $students->count())
                    </tbody>
                </table>
                <div class="page-break"></div>
                <table class="students-table">
                    <thead>
                        <tr>
                            <th style="width: 5%;">#</th>
                            <th style="width: 20%;">Student Details</th>
                            <th style="width: 15%;">Faculty & Degree</th>
                            <th style="width: 15%;">Contact Information</th>
                            <th style="width: 25%;">Hostel Information</th>
                            <th style="width: 20%;">Parent/Guardian Details</th>
                        </tr>
                    </thead>
                    <tbody>
                @endif
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-students">
            <h3>No students found</h3>
            <p>No students match the selected criteria.</p>
        </div>
    @endif

    <div class="footer">
        <p><strong>Sabaragamuwa University of Sri Lanka - Student Hostel Management System</strong></p>
        <p>Generated on {{ $generated_at }} | Total Students: {{ $total_students }} | Page automatically generated</p>
        <p>This is a computer-generated document. No signature required.</p>
    </div>
</body>
</html>
